apiVersion: v1
kind: Secret
metadata:
  name: keycloak-user-secret
type: kubernetes.io/basic-auth
stringData:
  username: keycloak_user
  password: keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: rtcms4j-user-secret
type: kubernetes.io/basic-auth
stringData:
  username: rtcms4j_user
  password: rtcms4j
