apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapEnv.name }}
  labels:
    {{- include "rtcms4j-web.labels" . | nindent 4 }}
{{- with .Values.configMapEnv.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
