apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelc-collector
  namespace: observing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelc-collector
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelc-collector
subjects:
  - kind: ServiceAccount
    name: otelc-collector
    namespace: observing
roleRef:
  kind: ClusterRole
  name: otelc-collector
  apiGroup: rbac.authorization.k8s.io
