protected-mode no

bind 0.0.0.0

aclfile /etc/valkey/valkey.acl

maxmemory 1gb
maxmemory-policy allkeys-lru

appendonly yes
appendfsync everysec

loglevel notice
logfile /data/valkey.log

save 900 1
save 300 10
save 60 10000