apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapFiles.name }}
  labels:
    {{- include "rtcms4j-core.labels" . | nindent 4 }}
data:
  {{- range .Values.configMapFiles.files }}
  {{ . }}: |-
    {{- $.Files.Get (printf "files/%s" .) | nindent 4 }}
  {{- end }}
