apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretEnv.name }}
  labels:
    {{- include "rtcms4j-notify.labels" . | nindent 4 }}
{{- with .Values.secretEnv.data }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
